version: '3.8'

services:
  websocket:
    image: node:14
    working_dir: /app
    volumes:
      - ./websocket:/app
    command: sh -c "npm install && npm start"
    ports:
      - "8080:8080"

  backend:
    image: node:14
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"

  auth:
    image: node:14
    working_dir: /app
    volumes:
      - ./auth:/app
    command: sh -c "npm install && npm start"
    ports:
      - "4000:4000"

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "8081:8081"

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: